export enum MicroserviceEvents {
  ON_EDGE_REMOVE = "ON_EDGE_REMOVE",
  ON_NODE_REMOVE = "ON_NODE_REMOVE",

  ON_SERVICES_CLICK = "ON_SERVICES_CLICK",
  ON_MODELS_CLICK = "ON_MODELS_CLICK",
  ON_DOCS_CLICK = "ON_DOCS_CLICK",
}
