// Auto-generated by Nimbly Client CLI
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using N1mbly.Common;
using N1mbly.Models;
using N1mbly.Models.Interfaces;

using Models;

namespace N1mbly.services.AuthController
{
  public class AuthController
  {
    private readonly IRemoteProxy _remoteProxy = new RemoteProxy();

    public async Task<Result<User>> GetLoggedInUser()
    {
      var result = await _remoteProxy.RemoteCallHandler(
        HttpMethod.Get,
        "http://localhost:3030/api" + "/auth",
        "/",
        new List<Argument>
        {
          
        }
      );
      return result;
    }

    public async Task<Result<User>> LogIn(User body)
    {
      var result = await _remoteProxy.RemoteCallHandler(
        HttpMethod.Post,
        "http://localhost:3030/api" + "/auth",
        "/login",
        new List<Argument>
        {
          new Argument { Source = "body", Name = "body", Value = body },
          
        }
      );
      return result;
    }

  }

}
