// Auto-generated by N1mbly Client CLI
using System.Collections.Generic;

namespace N1mbly.Models
{

  public class Peraa
  {
    public string Hello { get; set; }
    
  }

  public class Test
  {
    public string Username { get; set; }
    public string Password { get; set; }
    public List<Peraa> Peraas { get; set; }
    
  }

  public class Account
  {
    public string Username { get; set; }
    public string Password { get; set; }
    public List<Test> Tests { get; set; }
    
  }

  public class User
  {
    public string Name { get; set; }
    public string Surname { get; set; }
    public int? Age { get; set; }
    public Account Account { get; set; }
    
  }

  public class Pera
  {
    public string Username { get; set; }
    public string Password { get; set; }
    public bool Car { get; set; }
    
  }

}
