// Auto-generated by Nimbly Client CLI
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using N1mbly.Common;
using N1mbly.Models;
using N1mbly.Models.Interfaces;

using Models;

namespace N1mbly.services.NoviServis
{
  public class NoviServis
  {
    private readonly IRemoteProxy _remoteProxy = new RemoteProxy();

    public async Task<Result<object>> GetNesto()
    {
      var result = await _remoteProxy.RemoteCallHandler(
        HttpMethod.Get,
        "http://localhost:3030/api" + "/novi-servis",
        "/get-nesto",
        new List<Argument>
        {
          
        }
      );
      return result;
    }

  }

}
