// Auto-generated by Nimbly Client CLI
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using N1mbly.Common;
using N1mbly.Models;
using N1mbly.Models.Interfaces;

using Models;

namespace N1mbly.services.UserCrudController
{
  public class UserCrudController
  {
    private readonly IRemoteProxy _remoteProxy = new RemoteProxy();

    public async Task<Result<User>> FindOne(string id)
    {
      var result = await _remoteProxy.RemoteCallHandler(
        HttpMethod.Get,
        "http://localhost:3030/api" + "/users",
        "/:id",
        new List<Argument>
        {
          new Argument { Source = "path", Name = "id", Value = id },
          
        }
      );
      return result;
    }

    public async Task<Result<User>> FindMany()
    {
      var result = await _remoteProxy.RemoteCallHandler(
        HttpMethod.Get,
        "http://localhost:3030/api" + "/users",
        "/",
        new List<Argument>
        {
          
        }
      );
      return result;
    }

    public async Task<Result<User>> Create(User body)
    {
      var result = await _remoteProxy.RemoteCallHandler(
        HttpMethod.Post,
        "http://localhost:3030/api" + "/users",
        "/",
        new List<Argument>
        {
          new Argument { Source = "body", Name = "body", Value = body },
          
        }
      );
      return result;
    }

    public async Task<Result<User>> Update(string id, User body)
    {
      var result = await _remoteProxy.RemoteCallHandler(
        HttpMethod.Put,
        "http://localhost:3030/api" + "/users",
        "/:id",
        new List<Argument>
        {
          new Argument { Source = "path", Name = "id", Value = id },
          new Argument { Source = "body", Name = "body", Value = body },
          
        }
      );
      return result;
    }

    public async Task<Result<User>> Delete(string id)
    {
      var result = await _remoteProxy.RemoteCallHandler(
        HttpMethod.Delete,
        "http://localhost:3030/api" + "/users",
        "/:id",
        new List<Argument>
        {
          new Argument { Source = "path", Name = "id", Value = id },
          
        }
      );
      return result;
    }

  }

}
